### ISSUE TITLE
Adds to composer

### ISSUE THREAD

**Issue by Tpt** [digitalbazaar/php-json-ld#3]
[Composer](https://getcomposer.org) is the leading package manager for PHP and is very well integrated with GitHub, it would be very nice to be able to install this lib from it.

**Comment by dlongley** [comment]
Thanks @Tpt!

**Comment by Tpt** [comment]
Thank you very much. Could you add the package to Packagist in order to make it easily installable? https://packagist.org/packages/submit

**Comment by dlongley** [comment]
@Tpt, I did that when I did the merge ... is it not working properly?

**Comment by Tpt** [comment]
Oh. Sorry. Packagist search system seems to have an indexation lag so I didn't find the packages using it. But the package https://packagist.org/packages/digitalbazaar/json-ld seems to work properly. Thank you very much!

**Comment by dlongley** [comment]
Sure! :)
